/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Abhaypratap.Singh' at '11/8/18 12:10 AM' with Gradle 3.1
 *
 * @author Abhaypratap.Singh, @date 11/8/18 12:10 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
